### ISSUE TITLE
Convert tweets on tweet page from table to list-group

### ISSUE THREAD

**Issue by jawache** [jawache/botus#3]
On the tweet page we are showing a list of tweets as table items.

Let's convert them to bootstrap 4 list-group items like this: https://v4-alpha.getbootstrap.com/components/list-group/#custom-content

So convert this:

<img width="1050" alt="screenshot 2017-12-14 12 45 04" src="https://user-images.githubusercontent.com/897523/33992996-a3731ef2-e0cc-11e7-8852-a0ab4ab638a8.png">

To something like this:

<img width="490" alt="screenshot 2017-12-14 12 43 50" src="https://user-images.githubusercontent.com/897523/33992986-922e7646-e0cc-11e7-9e33-39b59ecb93a2.png">

**Comment by mtpultz** [comment]
Posted a [PR](https://github.com/jawache/botus/pull/7) for this issue
